### ISSUE TITLE
wine-winehq wont install

### ISSUE THREAD

**Issue by tjw0lf** [feren-OS/Dependency-Issue-Reporting#12]
Here is what i get in the terminal 

`tj@wolf:~$ sudo apt install --install-recommends winehq-staging
[sudo] password for tj: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 winehq-staging : Depends: wine-staging (= 5.0.0~bionic)
E: Unable to correct problems, you have held broken packages.
tj@wolf:~$ sudo apt install --install-recommends wine-staging
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine-staging : Depends: wine-staging-i386 (= 5.0.0~bionic)
                Depends: wine-staging-amd64 (= 5.0.0~bionic) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
tj@wolf:~$ 
`

wine-stable is the something can't install it

I always use wine-staging because Lutris recommends it. I have used it forever without any issues

Also in Synaptic when i try to install it from there its a red check mark.

**Comment by feren** [comment]
Turns out they decided to add a dependency on libfaudio0 outta and I only just found that out now from their website... *sigh* Added the new dependency to 'software'.

**Comment by tjw0lf** [comment]
WOW. They buggers. Yep thats what it looked like. Your Awesome knowing how to do that stuff. I did try to find it but i had bad luck knowing what to do. SO it will be in the update manager coming through for that packege right

**Comment by tjw0lf** [comment]
so what steps do i have to take for wine to work. i have libfaudio0 installed. But wine still showing it as grayed out

**Comment by feren** [comment]
?

The issue was that wine wasn't installing because that dependency was missing...

**Comment by tjw0lf** [comment]
it's still greyed out wine won't install. That package is installed

**Comment by tjw0lf** [comment]
Something is wonky with me ferenOS install? wine wont install its saying i need i386 packages and there not even listed in package manager wont be installed??? I don't know how to fix this

Its time to reinstall ferenOS? i think I would like to know what happend and know if can be fixed give me all commands can try to help me sort this out.

**Comment by tjw0lf** [comment]
I tested wine-stable installs fine i tested in virtaulbox and it works.

**Comment by feren** [comment]
`sudo dpkg --add-architecture i386` ?

**Comment by tjw0lf** [comment]
WHY ARE YOU CLOSING ALL MY TICKETS WHEN THERE NOT SOLVED??????
